# Derivando da imagem oficial do MySQL
FROM mysql:5.7


#  docker build -t mysql-course-udemy-go-cod3r .
#  docker run -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=cod3r -e MYSQL_USER=myuser -e MYSQL_PASSWORD=root mysql-course-udemy-go-cod3r
